### ISSUE TITLE
Can't delete old ticket when migrated v2.0.0 Beta -> 2.4.0

### ISSUE THREAD

**Issue by VoChiDanh** [DJj123dj/open-ticket#25]
i got this error why tried delete old ticket (v2.0.0) but ticket doesn't delete
```
ERROR: TypeError: Cannot read properties of null (reading 'text') | origin: uncaughtException STACK: TypeError: Cannot read properties of null (reading 'text')
    at F:\VoChiDanh\TicketSystem\core\ticketCloser.js:94:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.NEWcloseTicket (F:\VoChiDanh\TicketSystem\core\ticketCloser.js:89:9)
    at async Client.<anonymous> (F:\VoChiDanh\TicketSystem\core\closebuttons.js:273:9)

**Comment by DJj123dj** [comment]
yes, it is because there is a new system to close tickets. Normally it's recommended to delete all tickets before updating the bot

**Comment by DJj123dj** [comment]
i'm gonna add it to the wiki so that everyone knows that this needs to happen
